python script_1.py /lustre/t0/scratch/users/heloisa.mengisztki/ ~/output.csv
python script_1.py /lustre/t1/cl/lsst/pz_project/pcw_2023 ~/output.csv

In [124]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("~/output.csv")
df

,comment,process_id,start,end,duration,user,file_path
0,Test input mags truncated 4 decimal cases - sm...,fzboost_trunc4_chunk_150k,1900-07-15 20:33:39,1900-07-15 20:52:18,0:18:39,julia,/lustre/t1/cl/lsst/pz_project/pcw_2023/fzboost...
1,Test input mags with all decimal cases - small...,fzboost_all_dec_cases_chunk_150k_100x,1900-07-16 12:53:01,1900-07-16 16:08:13,3:15:12,julia,/lustre/t1/cl/lsst/pz_project/pcw_2023/fzboost...
2,Test input mags with all decimal cases - small...,bpz_all_dec_cases_chunk_150k,1900-07-15 20:06:21,1900-07-15 20:24:37,0:18:16,julia,/lustre/t1/cl/lsst/pz_project/pcw_2023/bpz_all...
3,Test large inputs (preproc max 150k rows),test_io_chunk_150k,1900-07-15 19:53:01,1900-07-15 20:23:42,0:30:41,julia,/lustre/t1/cl/lsst/pz_project/pcw_2023/test_io...
4,Test read and write from Lustre T1. FlexZBoost...,test_hardware_t1,1900-07-13 23:57:24,1900-07-14 00:33:33,0:36:09,julia,/lustre/t1/cl/lsst/pz_project/pcw_2023/test_ha...
5,Test input truncated 4 decimal cases - small f...,fzboost_trunc4_chunk_150k_100x,1900-07-15 21:00:54,1900-07-15 23:17:03,2:16:09,julia,/lustre/t1/cl/lsst/pz_project/pcw_2023/fzboost...
6,Test large inputs (preproc max 2M rows),test_io_chunk_2M,1900-07-15 18:34:16,1900-07-15 19:46:19,1:12:03,julia,/lustre/t1/cl/lsst/pz_project/pcw_2023/test_io...
7,Test read and write from Lustre T1. FlexZBoost...,test_hardware_t1,1900-07-13 21:19:41,1900-07-13 21:22:22,0:11:28,julia,/lustre/t1/cl/lsst/pz_project/pcw_2023/test_ha...
8,Test input mags truncated 4 decimal cases - sm...,bpz_trunc4_chunk_150k,1900-07-15 19:39:11,1900-07-15 20:02:32,0:23:21,julia,/lustre/t1/cl/lsst/pz_project/pcw_2023/bpz_tru...

In [122]:
df = pd.read_csv("~/test/test_fzboost_trunc4_chunk_150k.csv")
grouped_counts = df.groupby('host').size()

print(grouped_counts), len(df)

host
10.148.0.11    142
10.148.0.12    142
10.148.0.13    146
10.148.0.14    140
10.148.0.15    137
10.148.0.16    142
10.148.0.17    147
10.148.0.18    142
10.148.0.19    142
10.148.0.27    143
10.148.0.28    145
10.148.0.29    145
10.148.0.30     74
10.148.0.31     73
10.148.0.32     75
dtype: int64

(None, 1935)

In [123]:
df.head()

,task_id,time_begin,time_end,time_diff,file_name,chunks,host
0,1,1900-07-15 20:33:40,1900-07-15 20:36:24,164.0,objectTable_tract_3261_DC2_2_2i_runs_DP0_2_v23...,141838,10.148.0.17
1,16,1900-07-15 20:33:41,1900-07-15 20:36:29,168.0,objectTable_tract_3442_DC2_2_2i_runs_DP0_2_v23...,138651,10.148.0.17
2,46,1900-07-15 20:33:42,1900-07-15 20:36:41,179.0,objectTable_tract_3831_DC2_2_2i_runs_DP0_2_v23...,148416,10.148.0.17
3,61,1900-07-15 20:33:42,1900-07-15 20:36:48,186.0,objectTable_tract_3448_DC2_2_2i_runs_DP0_2_v23...,140009,10.148.0.17
4,76,1900-07-15 20:33:42,1900-07-15 20:36:48,186.0,objectTable_tract_3080_DC2_2_2i_runs_DP0_2_v23...,142410,10.148.0.17

In [93]:
df.groupby('file_name').size()

file_name
file_name                                                                                                   2
inprogress_objectTable_tract_2897_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_1_20220317T233937Z-part0     1
inprogress_objectTable_tract_2897_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_1_20220317T233937Z-part1     1
inprogress_objectTable_tract_2897_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_1_20220317T233937Z-part10    1
inprogress_objectTable_tract_2897_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_1_20220317T233937Z-part11    1
                                                                                                           ..
inprogress_objectTable_tract_5074_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_31_20220314T212509Z-part5    1
inprogress_objectTable_tract_5074_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_31_20220314T212509Z-part6    1
inprogress_objectTable_tract_5074_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_31_20220314T212509Z-part7    1
inprogress_objectTable_tract_5074_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_31_20220314T212509Z-part8    1
inprogress_objectTable_tract_5074_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_31_20220314T212509Z-part9    1
Length: 1936, dtype: int64

In [ ]:
'inprogress_objectTable_tract_3086_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_5_20220218T163030Z-part7.pq'

In [111]:
df = pd.read_csv("~/test/test_fzboost_trunc4_chunk_150k.csv")
grouped_counts = df.groupby('host').size()

df

,task_id,time_begin,time_end,time_diff,file_name,chunks,host
0,1,1900-07-15 20:33:40,1900-07-15 20:36:24,164.0,objectTable_tract_3261_DC2_2_2i_runs_DP0_2_v23...,141838,10.148.0.17
1,16,1900-07-15 20:33:41,1900-07-15 20:36:29,168.0,objectTable_tract_3442_DC2_2_2i_runs_DP0_2_v23...,138651,10.148.0.17
2,46,1900-07-15 20:33:42,1900-07-15 20:36:41,179.0,objectTable_tract_3831_DC2_2_2i_runs_DP0_2_v23...,148416,10.148.0.17
3,61,1900-07-15 20:33:42,1900-07-15 20:36:48,186.0,objectTable_tract_3448_DC2_2_2i_runs_DP0_2_v23...,140009,10.148.0.17
4,76,1900-07-15 20:33:42,1900-07-15 20:36:48,186.0,objectTable_tract_3080_DC2_2_2i_runs_DP0_2_v23...,142410,10.148.0.17
...,...,...,...,...,...,...,...
1930,1633,1900-07-15 20:42:13,1900-07-15 20:51:02,529.0,objectTable_tract_3447_DC2_2_2i_runs_DP0_2_v23...,145892,10.148.0.31
1931,1602,1900-07-15 20:41:59,1900-07-15 20:51:17,558.0,objectTable_tract_3263_DC2_2_2i_runs_DP0_2_v23...,149167,10.148.0.31
1932,1807,1900-07-15 20:43:59,1900-07-15 20:51:29,450.0,objectTable_tract_4031_DC2_2_2i_runs_DP0_2_v23...,148751,10.148.0.31
1933,1742,1900-07-15 20:43:22,1900-07-15 20:51:44,502.0,objectTable_tract_4641_DC2_2_2i_runs_DP0_2_v23...,146459,10.148.0.31
1934,1930,1900-07-15 20:44:45,1900-07-15 20:52:17,452.0,objectTable_tract_4030_DC2_2_2i_runs_DP0_2_v23...,139091,10.148.0.31

In [118]:
df = pd.read_csv("~/data/dp0.2_pre_processed_data.csv")
df

EmptyDataError: No columns to parse from file